window.noname_package={
	character:{
		jiuzisha:'九子魂',
		// standard:'标准',
		// refresh:'界限突破',
		// shenhua:'神话再临',
		// xinghuoliaoyuan:'星火燎原',
		// yijiang:'一将成名',
		// sp:'SP',
		// sp2:'系列专属',
		// extra:'神将',		
		// mobile:'移动版',
		// old:'怀旧',
		// diy:'DIY',
		// tw:'外服武将',
		// yxs:'英雄杀',
		// hearth:'炉石传说',
		// gwent:'昆特牌',
		// mtg:'万智牌',
		// ow:'守望先锋',
		// swd:'轩辕剑',
		// gujian:'古剑奇谭',
		// xianjian:'仙剑奇侠传',
	},
	card:{
		standard:'标准',
		extra:'军争',
		sp:'SP',
		guozhan:'国战',
		// zhulu:'逐鹿天下',
		// zhenfa:'阵法',
		// yunchou:'运筹帷幄',
		// swd:'轩辕剑',
		// gujian:'古剑奇谭',
		// hearth:'炉石传说',
		// gwent:'昆特牌',
		// mtg:'万智牌',
		// huanlekapai:'欢乐卡牌',
	},
	play:{
		// boss:'诸神降临',
		cardpile:'牌堆补充',
		// wuxing:'五行生克',
		// coin:'富甲天下',
	},
	mode:{
		identity:'身份',
		doudizhu:'斗地主',
		versus:'对决',
		guozhan:'国战',
		connect:'联机',
		single:'单挑',
		tafang:'塔防',
		chess:'战棋',
		brawl:'乱斗',
		stone:'炉石',
		boss:'挑战',
	},
	submode:{
		identity:{
			normal:'身份模式',
			zhong:'忠胆英杰',
			purple:'3v3v2',
		},
		guozhan:{
			normal:'国战模式',
			mingjiang:'明将国战'
		},
		versus:{
			four:'四人对抗',
			three:'统率三军',
			two:'欢乐成双',
			jiange:'守卫剑阁',
			siguo:'四国争霸',
			standard:'自由对决'
		},
		chess:{
			combat:'战棋模式',
			three:'战棋统率',
			leader:'战棋君主'
		},
		single:{
			normal:'新1v1',
		},
	},
	background:{
		jiuzi_bg:'九子魂',
		jiuzi_blue_bg:'九子蓝',
		jiuzi_red_bg:'九子红',
		jiuzi_green_bg:'九子绿',
		jiuzi_purple_bg:'九子紫',
		// jiuzi_carve_bg:'九子刻',
		// jiuzi_rotate_bg:'九子篆',
		skyCastle_bg:'云城',
		ol_bg:'龙纹',
		ring_bg:'金环',
		maidi_bg:'麦迪',
		aka_bg:'阿卡',
		xiaokui_bg:'小葵',
		mogu_bg:'蘑菇',
		huoyu_bg:'火域',
		xuedi_bg:'雪地',
		huangmo_bg:'荒漠',
		kuangchang_bg:'矿场',
		beach_bg:'海滩',
		greenland_bg:'绿地',
		market_bg:'集市',
		icyplace_bg:'冰台',
		snowfield_bg:'雪原',
		shenhai_bg:'深海',
		lifetree_bg:'生命树',
		honglian_bg:'红莲',
		huoshan_bg:'火山',
		bingshan_bg:'冰山',
		yanjiang_bg:'岩浆',
		bihai_bg:'碧海',
		haidi_bg:'海底',
		zhanhou_bg:'空之城',
		ningjing_bg:'宁静',
		nanman_bg:'南蛮',
		zhanhuo_bg:'战火',
		mingwang_bg:'冥王',
		minghou_bg:'冥后',
		jiuyu_bg:'酒域',
		xueyue_bg:'血月',
		casino_bg:'赌场',
		mingding_bg:'酩酊',
		roufa_bg:'肉伐',
		zhaoze_bg:'沼泽',
		rainforest_bg:'雨林',
		smoke_bg:'凝雾',
		firelion_bg:'火狮',
		chengbao_bg:'城堡',
		mingwang2_bg:'冥界',
		lodge_bg:'森林屋',
		// planetarian_bg:'星梦',
		// heaven_bg:'红烧',
		// kyoani_bg:'京都',
		// key_bg:'键社',
		// zhulin_bg:'竹林',
		shengshi_bg:'盛世',
		// taoyuan_bg:'桃园',
		huangtian_bg:'黄天',
		// september_bg:'九月',
		// yinxiang_bg:'印象',
		// zhanyun_bg:'战云',
		// beipan_bg:'背叛',
		// lanting_bg:'兰亭',
		// lingju_bg:'灵雎',
		// sanying_bg:'三英',
		// wangshi_bg:'往事',
		// xiongxin_bg:'雄心',
		// xinsha_bg:'新杀',
		// noname_bg:'璀璨',
		// wuming_bg:'无名',
	},
	music:{
		music_envSwordEnd:'主题曲',
		music_huoying:'功夫忍术',
		music_zhentian:'傲战长笛',
		music_limitless:'无限电子',
		music_FMIXChina:'红裙舞姬',
		music_sevenSwords:'七剑战歌',
		music_steinsDoor:'命运之门',
		music_mingyuetianya:'明月天涯',
		music_onepiece:'航海时代',
		music_conan:'柯南主题',
		music_fight:'战斗兄弟',
		music_void:'如履薄冰',
		music_pirate:'海盗天下',
		music_xianjian:'奇缘剑仙',
		music_weare:'海盗宝藏',
		music_buwu:'天下布武',
		music_ninelie:'王冠之战',
		music_steinsOverture:'命运序曲',
		music_taoyuanjieyi:'桃园结义',
		music_siji:'四季',
		music_dongzhuojinjing:'董卓进京',
		music_diaochanmeiren:'貂蝉美人', 
		music_sanyingzhanlvbu:'三英战吕布',
		music_chuanliubuxi:'川流不息', 
		music_zhugechushan:'卧龙出山',
		music_shezhanqunru:'舌战群儒', 
		music_wanchengzhan:'宛城之战', 
		music_changbanpo:'长坂坡', 
		music_sanguoguijing:'三国归晋', 
		music_jifeng:'祭风',
		music_jilve:'极略',
		music_feelThisMoment:'性感女高音',
		music_attraction:'魅力无限',
		music_wordKingdom:'文字国历险',
		music_chinaBoy:'中华小子',
		music_envSwordStart:'环保剑片头',
		music_qihun:'棋魂',
		music_yilihuoying:'仪礼火影',
		music_danji:'千里走单骑',
		music_yxsbgm:'英雄杀',
		music_yxsSelect:'英雄杀选择',
		music_default:'三国杀',
		music_scary:'恐怖异世界',
		// music_phliosophy:'Philosophy of ours',
		// music_diaochan:'貂蝉',
		// music_shezhan:'舌战群儒',
	},
	font:{
		xiaozhuan:'小篆',
		xinwei:'新魏',
		huangcao:'黄草',
		yuanli:'楷体',
		xingkai:'行楷',
		shousha:'手杀',
	},
	theme:{
		woodden:'木纹',
		music:'音乐',
		simple:'简约'
	}
};
